version: 1.2
workflows:
  - name: pbsv-discover
    subclass: WDL
    primaryDescriptorPath: /wdl/pbsv_discover.wdl
    testParameterFiles: /inputs/pbsv_discover.inputs.json
    authors:
      - name: "Juniper Lake"
        email: "jlake@pacificbiosciences.com"
