version: 1.2
workflows:
  - name: single-sample
    subclass: WDL
    primaryDescriptorPath: /workflows/single_sample.wdl
    testParameterFiles: /inputs/single_sample.inputs.json
    authors:
      - name: "Juniper Lake"
        email: "jlake@pacificbiosciences.com"
