version: 1.2
workflows:
  - name: call-variants-single-sample
    subclass: WDL
    primaryDescriptorPath: /workflows/call_variants.wdl
    testParameterFiles: /inputs/call_variants.inputs.json
    authors:
      - name: "Juniper Lake"
        email: "jlake@pacificbiosciences.com"
